#%RAML 1.0
title: Customer Process API
version: v1
protocols:
  - HTTP
  - HTTPS
description: Techhunting mulesoft code challenge Customer Process API

######################################################
# WHO WHEN       WHY
# FF  07/23/2026 Initial Definition
######################################################

types:
  customer: !include datatypes/customer.raml

/customers:
  /process:
    post:
      description: Process a customer payload and return canonical customer JSON
      body:
        application/json:
          type: customer
          examples: 
            jsonSuccess: !include examples/customers-process-request-success-example.json
            invalidDOBError: !include examples/customers-process-request-invalid-dob-error-example.json
        application/xml:
          type: customer
          examples: 
            xmlSuccess: !include examples/customers-process-request-success-example.xml
            invalidNameError: !include examples/customers-process-request-invalid-name-error-example.xml
      responses:
        200:
          description: Canonical customer object
          body:
            application/json:
              type: object
              examples:
                internalCustomerSuccess: !include examples/customers-process-response-success-example.json
                externalCustomerSuccess: !include examples/customers-process-response-external-success-example.json
        400:
          description: Validation error
          body:
            application/json:
              type: object
              examples:
                fieldValidationError: !include examples/customers-process-response-name-error-example.json
                dateOfBirthError: !include examples/customers-process-response-dob-error-example.json 
          
    